// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyACy5rXfXIJV_RnLtFsieFFFUK2PofAiIY',
    appId: '1:976293627311:web:885f9752ae6a7b99609b5a',
    messagingSenderId: '976293627311',
    projectId: 'project-66720',
    authDomain: 'project-66720.firebaseapp.com',
    storageBucket: 'project-66720.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCq-FrWehN9jdQh9gTZv12T34agw-FMa6o',
    appId: '1:976293627311:android:515ae54380056cf2609b5a',
    messagingSenderId: '976293627311',
    projectId: 'project-66720',
    storageBucket: 'project-66720.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDSD_RN4yi-DIeZkPmiRZaACVY8qbbg0cQ',
    appId: '1:976293627311:ios:3d4e67ac6f6d563c609b5a',
    messagingSenderId: '976293627311',
    projectId: 'project-66720',
    storageBucket: 'project-66720.appspot.com',
    iosClientId: '976293627311-fc7h9vu425f91eg3g35mm0lb2g1vd7oj.apps.googleusercontent.com',
    iosBundleId: 'com.example.project',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDSD_RN4yi-DIeZkPmiRZaACVY8qbbg0cQ',
    appId: '1:976293627311:ios:3d4e67ac6f6d563c609b5a',
    messagingSenderId: '976293627311',
    projectId: 'project-66720',
    storageBucket: 'project-66720.appspot.com',
    iosClientId: '976293627311-fc7h9vu425f91eg3g35mm0lb2g1vd7oj.apps.googleusercontent.com',
    iosBundleId: 'com.example.project',
  );
}
